defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      discord_url: "https://discord.gg/QZp4AWz"
      map_url: "https://map.akenland.com"
      mc_version: "Minecraft Java Edition 1.16.5"
  - scope:
      path: "*.md"
    values:
      layout: "page"