markdown: kramdown
kramdown:
  parse_block_html: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      discord_url: "https://discord.akenland.com"
      map_url: "https://map.akenland.com"
      mc_version: "Minecraft Java Edition 1.21.4"
  - scope:
      path: "*.md"
    values:
      layout: "page"
